# Minimal Docker Compose configuration for quick testing
services:
  # Gateway only (no UI, monitoring, etc.)
  rdagent-gateway:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: rdagent-gateway-minimal
    ports:
      - "8001:8000"
    environment:
      - RD_AGENT_HOST=0.0.0.0
      - RD_AGENT_PORT=8000
      - RD_AGENT_DEBUG=false
      - RD_AGENT_AUTH_ENABLED=false
      - RD_AGENT_LOG_LEVEL=INFO
      - RD_AGENT_DEFAULT_SCENARIO=data_science
      - RD_AGENT_DEFAULT_COMPETITION=titanic
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - CHAT_MODEL=${CHAT_MODEL:-gpt-4o}
      - EMBEDDING_MODEL=${EMBEDDING_MODEL:-text-embedding-3-small}
      - KAGGLE_USERNAME=${KAGGLE_USERNAME:-}
      - KAGGLE_KEY=${KAGGLE_KEY:-}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    driver: bridge